### ISSUE TITLE
using "--boxed" prevents viewing stdout with "-s"

### ISSUE THREAD

**Issue by samuelcolvin** [pytest-dev/pytest-xdist#106] opened 2017-01-05 10:24 UTC
Lets say I have a test setup up

```python
def test_test():
    print('this is test_test')
```

If I run it with `pytest -s` I get "this is test_test" printed.

If instead I run it with `pytest -s --boxed`, "this is test_test" is not printed.

If this is intended behaviour it would be useful to document it prominently as I spent some time working out why "-s wasn't working".

I'm running latest pytest and pytest-xdist, the project is OS so I can give exact setup detail if required.

**Comment by RonnyPfannschmidt** [comment] 2017-01-05 13:05
this is intended behavior, boxed will be moved to a own pypi package in the next major release

**Comment by danlamanna** [comment] 2017-10-03 19:48
Any idea for a timeline of this? I also spent a bit of time trying to figure out why `-s` wasn't working.

**Comment by RonnyPfannschmidt** [comment] 2017-10-03 20:09
boxed got moved to pytest-forked, im not planning to work on enabling this as the current design of boxed prevents it

**Comment by RonnyPfannschmidt** [comment] 2019-07-23 08:11
closing as wontfix

**Closed by RonnyPfannschmidt** 2019-07-23 08:11 UTC
