### ISSUE TITLE
Slave 'gw0' crashed when using pytest.exit()

### ISSUE THREAD

**Issue by rosariomgomez** [pytest-dev/pytest-xdist#86] opened 2016-08-29 18:38 UTC
Environment:
python 3.5.2
pytest==2.9.2
pytest-xdist==1.15.0
pytest-randomly==1.0.0

When using the method `pytest.exit(msg)` to immediately exit the test run, I've got the following error (for any value of n):
`Slave 'gw0' crashed while running 'test_name'
!!!!! xdist.dsession.Interrupted: <SlaveController gw0> received keyboard-interrupt !!!!`

Am I missing any other parameter (besides -n) that I should be passing? 

Thanks for your help! Please, let me know if there is any extra information I can provide that could help to debug the issue.

**Comment by nicoddemus** [comment] 2016-08-29 21:56
Thanks for the report.

That seems like a bug in `xdist`, it should handle the `pytest.Exit` exception correctly.

**Comment by Daenyth** [comment] 2016-09-14 15:04
This is is fairly painful for me, as I use xdist on our CI for integration tests - failed setup (errors in migration, etc) aborts the pytest run but the errors don't get reported nicely to the dev.

If there's some clear guidance on how to approach this I might be able to put in a PR

**Comment by nicoddemus** [comment] 2016-09-14 15:29
@Daenyth are they aborted by `pytest.Exit` or some other error?

**Comment by Daenyth** [comment] 2016-09-14 16:34
I invoke `pytest.exit(failmsg)`

When I omit the `-n` parameter I get back the message on the summary line

**Comment by nicoddemus** [comment] 2016-09-14 16:36
Thanks, I was asking just to know for sure if it was crashing due to something else.

**Comment by Daenyth** [comment] 2016-09-27 17:33
@nicoddemus Do you think this is a reasonably easy fix to contribute? I think a test case shouldn't be too hard to create showing the issue.

**Comment by nicoddemus** [comment] 2016-09-28 21:43
A PR with an xfail test would be very welcome!

**Comment by feuillemorte** [comment] 2018-01-19 09:37
It's difficult to fix this issue because pytest sends `{'exitstatus': 2}` to xdist and xdist think that it is keyboard-interrupt:

pytest (main.py)
```
        except KeyboardInterrupt:
            excinfo = _pytest._code.ExceptionInfo()
            if initstate < 2 and isinstance(excinfo.value, exit.Exception):
                sys.stderr.write('{0}: {1}\n'.format(
                    excinfo.typename, excinfo.value.msg))
            config.hook.pytest_keyboard_interrupt(excinfo=excinfo)
            session.exitstatus = EXIT_INTERRUPTED
```

xdist (dsession.py):
```
    def slave_slavefinished(self, node):
        """Emitted when node executes its pytest_sessionfinish hook.

        Removes the node from the scheduler.

        The node might not be in the scheduler if it had not emitted
        slaveready before shutdown was triggered.
        """
        self.config.hook.pytest_testnodedown(node=node, error=None)
        if node.slaveoutput['exitstatus'] == 2:  # keyboard-interrupt
            self.shouldstop = "%s received keyboard-interrupt" % (node,)
            self.slave_errordown(node, "keyboard-interrupt")
            return
        if node in self.sched.nodes:
            crashitem = self.sched.remove_node(node)
            assert not crashitem, (crashitem, node)
        self._active_nodes.remove(node)
```
Maybe we can except smth like `except Exit: session.exitstatus = ANOTHER_STATUS`, but this code didn't worked for me

So, if smb knows how to fix it easy please, give me an advice)

**Comment by nicoddemus** [comment] 2018-01-20 12:35
@feuillemorte good point, I see that `Exit` is a subclass of `KeyboardInterrupt`, which seems weird at first glance. Regardless, we should catch and treat `Exit` differently in `_pytest.main.py` to gracefully exit stating that it was caused by an explicit `pytest.exit()` call.

**Comment by feuillemorte** [comment] 2018-01-23 12:52
I'll create a task to pytest (which branch? master?) but I really don't know how to pass message to xdist module from pytest:

https://github.com/pytest-dev/pytest/blob/0d96a5bf9059e51324ac24ec24d68af1c35db6d8/_pytest/main.py#L110-L116

https://github.com/pytest-dev/pytest-xdist/blob/3098f277315bcbe7b081273ba2bace88a1ca3a13/xdist/remote.py#L40-L44

**Comment by blueyed** [comment] 2019-11-21 19:43
Might be fixed in pytest: https://github.com/pytest-dev/pytest/issues/3144#issuecomment-557242166

**Closed** 2022-08-16 07:54 UTC
Labels: bug
