### ISSUE TITLE
AttributeError: 'WorkerController' object has no attribute 'slaveinput'

### ISSUE THREAD

**Issue by bruceduhamel** [pytest-dev/pytest-xdist#577] opened 2020-08-14 15:23 UTC
I recently upgraded from pytest-xdist 1.34.0 to 2.0.0 and found that tests always fail with the new version. I pinned the previous version as a workaround.

I've tested on Ubuntu 18.04 and the circle [CI docker image for python 3.7.6](https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/python/images/3.7.6/Dockerfile)

If I remove --cov=project_folder (project_folder was redacted), the tests run successfully.

```
pytest --numprocesses=auto --cov=project_folder test itest

============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /root/repo
plugins: xdist-2.0.0, forked-1.3.0, cov-2.10.0
gw0 C / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I / gw8 I / gw9 I / gw10 I / gw11 I / gw12 I / gw13 I / gw14 I / gw15 I / gw16 I / gw17 IINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/_pytest/main.py", line 238, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/xdist/dsession.py", line 78, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/xdist/workermanage.py", line 65, in setup_nodes
INTERNALERROR>     return [self.setup_node(spec, putevent) for spec in self.specs]
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/xdist/workermanage.py", line 65, in <listcomp>
INTERNALERROR>     return [self.setup_node(spec, putevent) for spec in self.specs]
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/xdist/workermanage.py", line 73, in setup_node
INTERNALERROR>     node.setup()
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/xdist/workermanage.py", line 260, in setup
INTERNALERROR>     self.config.hook.pytest_configure_node(node=self)
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pytest_cov/plugin.py", line 239, in pytest_configure_node
INTERNALERROR>     self.cov_controller.configure_node(node)
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pytest_cov/engine.py", line 274, in configure_node
INTERNALERROR>     workerinput(node).update({
INTERNALERROR>   File "/root/repo/venv/lib/python3.7/site-packages/pytest_cov/compat.py", line 42, in fn
INTERNALERROR>     return getattr(obj, attr, *args)
INTERNALERROR> AttributeError: 'WorkerController' object has no attribute 'slaveinput'
```

**Comment by graingert** [comment] 2020-08-14 15:26
hello @bruceduhamel  this is an issue in pytest-cov, fixed in the unreleased https://github.com/pytest-dev/pytest-cov/pull/412

**Comment by ssbarnea** [comment] 2020-08-14 15:42
I can confirm the same breakage. I think this should have not being release without assuring it works with pytest-cov. Based on how many are affected it would make sense to remove the release from pip, and avoid ruining this weekend.

A major release should not be made on Friday.

**Comment by The-Compiler** [comment] 2020-08-14 15:42
Closing this as this needs to be fixed from pytest-cov's side (looks like only a new release is needed).

**Comment by graingert** [comment] 2020-08-14 15:42
>  to remove the release from pip

a yank?

**Closed** 2020-08-14 15:41 UTC

**Comment by nicoddemus** [comment] 2020-08-14 15:54
> A major release should not be made on Friday.

To be fair, we really did our homework in https://github.com/pytest-dev/pytest-xdist/pull/541 by contacting all affected repositories, contributing PRs, etc. And that has been resolved for awhile now.

It would be great if `pytest-cov` could make a new release to fix this, and avoid further noise by having to yank that version from `PyPI`.

cc @ionelmc
