### ISSUE TITLE
Feature Request: Threads instead of Processes

### ISSUE THREAD

**Issue by mkmoisen** [pytest-dev/pytest-xdist#904] opened 2023-05-12 00:13 UTC
My regression tests are completely IO bound. 

pytest-xdist allows me to run my tests concurrently by launching processes. While this works fine, it is a bit expensive, and somewhat limits my concurrency because I don't want to launch 20+ processes.

It would be great if pytest-xdist allowed an option to specify the number of threads, in addition to the number of processes:

    pytest -n 4 --threads 5

Could this be a possible enhancement to pytest-xdist?

**Comment by nicoddemus** [comment] 2023-05-12 01:31
Hi @mkmoisen,

This is a duplicate of #11, but in short it is really not possible in xdist, as pytest itself is only single threaded.

Closing this one, feel free to follow up with more questions in #11 (in order to not fragment the discussion).

**Closed by nicoddemus** 2023-05-12 01:31 UTC
