### ISSUE TITLE
Test may be blocked by one xdist subprocess

### ISSUE THREAD

**Issue by matthiasha** [pytest-dev/pytest-xdist#244] opened 2017-11-15 16:06 UTC
With the following code I'm able to reproduce an issue which I'm also observing on a larger scale of tests:
```python
import pytest
import time

@pytest.mark.parametrize('x', range(1000))
def test_xdist(x):
    if x == 0:
        time.sleep(10)
```
Note: according to the code I expect only one test (and thus only one xdist node) to be blocked -- instead, the whole Pytest execution blocks for 10 seconds.

I would expect that all other tests finish while this one test is running for 10 seconds.

To visualize how tests are blocked, I pressed on the "b" key while the progress paused:
```
❯❯❯ pytest -n10                     
========================== test session starts ===========================
platform linux -- Python 3.5.2+, pytest-3.2.5, py-1.5.1, pluggy-0.4.0
rootdir: /tmp/xdist-test, inifile:
plugins: forked-0.2, xdist-1.20.1
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I / gw8 I / gwgw0 C / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I / gw8 I / gwgw0 C / gw1 C / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I / gw8 I / gwgw0 C / gw1 C / gw2 C / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I / gw8 I / gwgw0 C / gw1 C / gw2 C / gw3 C / gw4 I / gw5 I / gw6 I / gw7 I / gw8 I / gwgw0 C / gw1 C / gw2 C / gw3 C / gw4 C / gw5 I / gw6 I / gw7 I / gw8 I / gwgw0 C / gw1 C / gw2 C / gw3 C / gw4 C / gw5 C / gw6 I / gw7 I / gw8 I / gwgw0 C / gw1 C / gw2 C / gw3 C / gw4 C / gw5 C / gw6 C / gw7 I / gw8 I / gwgw0 C / gw1 C / gw2 C / gw3 C / gw4 C / gw5 C / gw6 C / gw7 C / gw8 I / gwgw0 C / gw1 C / gw2 C / gw3 C / gw4 C / gw5 C / gw6 C / gw7 C / gw8 C / gwgw0 C / gw1 C / gw2 C / gw3 C / gw4 C / gw5 C / gw6 C / gw7 C / gw8 C / gwgw0 ok / gw1 C / gw2 C / gw3 C / gw4 C / gw5 C / gw6 C / gw7 C / gw8 C / ggw0 ok / gw1 ok / gw2 C / gw3 C / gw4 C / gw5 C / gw6 C / gw7 C / gw8 C / gw0 [1000] / gw1 ok / gw2 C / gw3 C / gw4 C / gw5 C / gw6 C / gw7 C / gw8 gw0 [1000] / gw1 ok / gw2 C / gw3 ok / gw4 C / gw5 C / gw6 C / gw7 C / gw8gw0 [1000] / gw1 [1000] / gw2 C / gw3 ok / gw4 C / gw5 C / gw6 C / gw7 C /gw0 [1000] / gw1 [1000] / gw2 C / gw3 ok / gw4 ok / gw5 C / gw6 C / gw7 C gw0 [1000] / gw1 [1000] / gw2 ok / gw3 ok / gw4 ok / gw5 C / gw6 C / gw7 Cgw0 [1000] / gw1 [1000] / gw2 ok / gw3 ok / gw4 ok / gw5 ok / gw6 C / gw7 gw0 [1000] / gw1 [1000] / gw2 ok / gw3 ok / gw4 ok / gw5 ok / gw6 ok / gw7gw0 [1000] / gw1 [1000] / gw2 ok / gw3 ok / gw4 ok / gw5 ok / gw6 ok / gw7gw0 [1000] / gw1 [1000] / gw2 ok / gw3 [1000] / gw4 ok / gw5 ok / gw6 ok /gw0 [1000] / gw1 [1000] / gw2 ok / gw3 [1000] / gw4 [1000] / gw5 ok / gw6 gw0 [1000] / gw1 [1000] / gw2 ok / gw3 [1000] / gw4 [1000] / gw5 ok / gw6 gw0 [1000] / gw1 [1000] / gw2 ok / gw3 [1000] / gw4 [1000] / gw5 [1000] / gw0 [1000] / gw1 [1000] / gw2 ok / gw3 [1000] / gw4 [1000] / gw5 [1000] / gw0 [1000] / gw1 [1000] / gw2 ok / gw3 [1000] / gw4 [1000] / gw5 [1000] / gw0 [1000] / gw1 [1000] / gw2 [1000] / gw3 [1000] / gw4 [1000] / gw5 [1000gw0 [1000] / gw1 [1000] / gw2 [1000] / gw3 [1000] / gw4 [1000] / gw5 [1000gw0 [1000] / gw1 [1000] / gw2 [1000] / gw3 [1000] / gw4 [1000] / gw5 [1000gw0 [1000] / gw1 [1000] / gw2 [1000] / gw3 [1000] / gw4 [1000] / gw5 [1000] / gw6 [1000] / gw7 [1000] / gw8 [1000] / gw9 [1000]
scheduling tests via LoadScheduling
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................bbbbbbbbbbbbbbbbbbbbbb..................................
====================== 1000 passed in 10.81 seconds ======================
```

I might further investigate and try to fix this issue. Please let me know if this is expected.

**Comment by flub** [comment] 2018-04-21 09:10
Hi,

I've tried to reproduce this, with `range(10)` and `-n5` to more easily see what's going on and this behaves mostly fine from what I can observe.  You can see this more clearly when running the tests with `-v` as that shows you which process was running which test.  If you do this you'll observe that **most** of the tests which run after the blocking happened are all from the same gateway, actually from gw0 since the `x == 0` condition will make sure it's always gw0 which blocks.  In fact when running with only `range(10)` **all** of the tests after the blocking are fro gw0, the *most* part is another scheduler corner case.

This is entirely expected with how the scheduler works currently.  It asks all the processes to collect the tests and then gives batches of the tests to each process.  It waits for the processes to return the results.  So in the `range(10)` `-n5` case the batch gw0 gets is `x=0`, `x=1`.  The master process has no idea that the first one will block, so gw0 starts executing this and can not report back to the master until the entire batch is done.  And when the results of that batch finally come in the suite is finished.

The reason for this batching behaviour is that it is way to expensive, usually, to ask each process to run one test at a time.  So this compromise of the default LoadScheduler is usually reasonable.  Though if there's a good reason this is not reasonable in your case you can write a new scheduler for your usecase in a plugin I believe.  There may be other features in schedulers like marking specific tests which I've currently forgotten.  Basically you'll want to dig into the schedulers if you want to optimise your usecase here.

In light of this I'm going to close this as "working as intended" for now.

**Closed by flub** 2018-04-21 09:10 UTC
Labels: help wanted
