### ISSUE TITLE
pytest hangs before running tests

### ISSUE THREAD

**Issue by ipanousis** [pytest-dev/pytest-xdist#61] opened 2016-05-28 12:58 UTC
Hi all,

I'm running "py.test -k test_authenticated_user_cannot_index_ -n2 --max-slave-restart=0" hangs before running any tests.

The process tree shows a waiting STDIN for each of the workers:
```
$ pstree -hap 15994
py.test,15994 /root/.local/bin/py.test -k test_authenticated_user_cannot_index_ -n2 --max-slave-restart=0
  ├─python3.5,16010 -u -c import sys;exec(eval(sys.stdin.readline()))
  │   └─{python3.5},16011
  └─python3.5,16012 -u -c import sys;exec(eval(sys.stdin.readline()))
      └─{python3.5},16013
```

The output until the hanging point shows:

```
============================= test session starts ==============================
platform linux -- Python 3.5.0, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /lws, inifile: setup.cfg
plugins: nameko-2.2.0, cov-2.2.1, rerunfailures-2.0.0, flakes-1.0.1, pep8-1.0.6, xdist-1.14
gw0 I / gw1 I
```

The traceback after hitting Ctrl-C adds:

```
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/eventlet/hubs/hub.py", line 457, in fire_timers
    timer()
  File "/root/.local/lib/python3.5/site-packages/eventlet/hubs/timer.py", line 58, in __call__
    cb(*args, **kw)
  File "/root/.local/lib/python3.5/site-packages/eventlet/semaphore.py", line 145, in _do_acquire
    waiter.switch()
greenlet.error: cannot switch to a different thread
[gw0] node down: Not properly terminated
Slave restarting disabled
gw0 [1] / gw1 [2434]

scheduling tests via LoadScheduling
[gw1] node down: keyboard-interrupt
Slave restarting disabled

==================================== ERRORS ====================================
_____________________________ ERROR collecting gw0 _____________________________
Different tests were collected between gw1 and gw0. The difference is:
--- gw1

+++ gw0

@@ -1,2434 +1 @@
...
all of the test names
...

 xdist.dsession.Interrupted: <SlaveController gw1> received keyboard-interrupt !
=========================== 1 error in 34.28 seconds ===========================
```

Versions and plugins:
```
flaky==3.1.1
py==1.4.31
pytest==2.9.1
pytest-flakes==1.0.1
pytest-pep8==1.0.6
pytest-cov==2.2.1
pytest-rerunfailures==2.0.0
coverage==4.0.3
```

Please let me know if there's any other info I could collect.

Thanks!

Yannis

**Comment by nicoddemus** [comment] 2016-05-30 23:59
Hi @ipanousis, thanks for taking the time to provide this information.

While you provided plenty of info, I can't tell what might be the problem. Could you share a fully reproducible example which demonstrates the problem?

Did you try this command line on a set of dummy tests? That would be a way to pinpoint if the problem is in your environment somehow or related to the real code under test.

**Comment by RonnyPfannschmidt** [comment] 2016-05-31 07:05
since eventlet is involved, please show the full list of packages, it is in the traceback and not in your list

**Comment by RonnyPfannschmidt** [comment] 2016-06-17 10:18
closing this one as incomplete, in particular since #71 seems more comprehensible

**Closed by RonnyPfannschmidt** 2016-06-17 10:18 UTC
