### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'float'

### ISSUE THREAD

**Issue by radeklat** [pytest-dev/pytest-xdist#367] opened 2018-11-09 12:03 UTC
I consistently observe a crash when running pytest with xdist. I tried different versions of xdist (from 1.24.0 down to 1.20.1) and all have the same issue. Is it possibly a configuration issue? The command is:

`pytest -n auto tests/unit`

And the crash (with base path obscured) below:

```platform linux -- Python 3.6.6, pytest-3.10.0, py-1.7.0, pluggy-0.8.0
rootdir: <BASEPATH>, inifile:
plugins: xdist-1.24.0, forked-0.2, cov-2.6.0
gw0 [3351] / gw1 [3351] / gw2 [3351] / gw3 [3351]
scheduling tests via LoadScheduling
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/_pytest/main.py", line 185, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/_pytest/main.py", line 225, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/xdist/dsession.py", line 115, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/xdist/dsession.py", line 138, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/xdist/dsession.py", line 235, in worker_collectionfinish
INTERNALERROR>     self.sched.schedule()
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/xdist/scheduler/load.py", line 230, in schedule
INTERNALERROR>     if not self._check_nodes_have_same_collection():
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/xdist/scheduler/load.py", line 284, in _check_nodes_have_same_collection
INTERNALERROR>     self.config.hook.pytest_collectreport(report=rep)
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/_pytest/terminal.py", line 491, in pytest_collectreport
INTERNALERROR>     self.report_collect()
INTERNALERROR>   File "<BASEPATH>/.venv/lib/python3.6/site-packages/_pytest/terminal.py", line 500, in report_collect
INTERNALERROR>     if self._collect_report_last_write > t - 0.5:
INTERNALERROR> TypeError: '>' not supported between instances of 'NoneType' and 'float'```

**Comment by RonnyPfannschmidt** [comment] 2018-11-09 12:06
duplicate of https://github.com/pytest-dev/pytest/issues/4329

**Closed by RonnyPfannschmidt** 2018-11-09 12:06 UTC
