### ISSUE TITLE
How to see output of tests when running with pytest-xdist ? (-s flag)

### ISSUE THREAD

**Issue by david-fliguer-ws** [pytest-dev/pytest-xdist#354] opened 2018-10-16 06:13 UTC
Hi, I noticed that when running pytest -n auto -s then despite I am passing -s there is no output.

I read that a possible workaround is to redirect on the code the standard error to the standard output (Or something like that) is there any other option, something more clean ?

Thanks and great job with pytest-xdist !!!

**Comment by RonnyPfannschmidt** [comment] 2018-10-16 06:50
xdist cannot support `-s` for technical reasons wrt the process execution mechanism, as such it cant be supported right now

**Comment by david-fliguer-ws** [comment] 2018-10-17 06:13
So the workaround by now is this one ? 

https://stackoverflow.com/questions/27006884/pytest-xdist-without-capturing-output

set a conftest.py that contains this code ?

sys.stdout = sys.stderr

Where should that conftest.py sit and which scope should it have ?
What can be the side effects of this ?

Thanks a lot,

David

**Comment by nicoddemus** [comment] 2018-10-18 15:31
Hi David,

You can place that in any file which is imported during the test run, the root `conftest.py` could be used for that. As side effects, it really depends on your code and libraries you have, as you are effectively replacing `sys.stdout` by `sys.stderr`

**Comment by boxed** [comment] 2018-10-24 13:37
Not swallowing output is a pretty important thing! I have some other problem with a bug/misfeature in xdist and it was hidden by this, so when running with xdist it just said "no tests" when in fact there was an error printed by the worker. This is super bad.

Now, when I fixed this, it's still broken and gives me no tests, but that's another problem I'm still investigating.

**Comment by nicoddemus** [comment] 2018-10-24 14:18
@RonnyPfannschmidt just to confirm, `execnet` uses `stdout` and `stderr` for its communication mechanism?

**Comment by david-fliguer-ws** [comment] 2018-11-14 11:35
Hi, is it possible that sometimes xdist "mixes" the output and I see in a test output that should be from another test ?

It is kind of strange but I think it might be happening.

When I run same tests without pytest-xdist it never happens...

Any idea ?

**Comment by nicoddemus** [comment] 2019-01-24 22:53
Closing as duplicate of https://github.com/pytest-dev/pytest-xdist/issues/82

**Closed by nicoddemus** 2019-01-24 22:53 UTC
Labels: question

**Comment by draganrakas** [comment] 2019-08-03 22:51
> Hi, is it possible that sometimes xdist "mixes" the output and I see in a test output that should be from another test ?
> 
> It is kind of strange but I think it might be happening.
> 
> When I run same tests without pytest-xdist it never happens...
> 
> Any idea ?

Did you ever end up resolving this issue? I see this as well, especially when using a larger number of workers. Probably because stdout is shared across all workers... but then how do we print information unique to each test case?

**Comment by palvarezcordoba** [comment] 2022-10-11 11:55
The workaraound `sys.stdout = sys.stderr` worked for me, but it made the output really messy, idk why.
I have this in my conftest.py and this allows me to use print but it does not make the output messy.
```python
@pytest.fixture(scope="session", autouse=True)
def fix_print():
    """
    pytest-xdist disables stdout capturing by default, which means that print() statements
    are not captured and displayed in the terminal.
    That's because xdist cannot support -s for technical reasons wrt the process execution mechanism
    https://github.com/pytest-dev/pytest-xdist/issues/354
    """
    original_print = print
    with patch("builtins.print") as mock_print:
        mock_print.side_effect = lambda *args, **kwargs: original_print(*args, **{"file": sys.stderr, **kwargs})
        yield mock_print
```

@nicoddemus It would be nice to add this workaround, or one similar in https://pytest-xdist.readthedocs.io/en/latest/known-limitations.html

**Comment by RonnyPfannschmidt** [comment] 2022-10-11 14:22
The outputs of multiple pytests would stream into the terminal causing a total mess

Any workaround / fix for that is a major piece of work

I'm not aware of someone that currently can and will commit to doing it

**Comment by ikamensh** [comment] 2024-11-17 13:32
Is it also difficult to raise an explicit exception / warning if passing -s flag with xdist active? it would at least save people time researching why behaviour is not what they think it should be.
