### ISSUE TITLE
2.1.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [pytest-dev/pytest-xdist#601] opened 2020-10-13 02:50 UTC
Just one unit ..
```
+ cd pytest-xdist-2.1.0
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-xdist-2.1.0-2.fc34.x86_64/usr/lib/python3.8/site-packages
+ pytest
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.3, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/tkloczko/rpmbuild/BUILD/pytest-xdist-2.1.0/.hypothesis/examples')
rootdir: /home/tkloczko/rpmbuild/BUILD/pytest-xdist-2.1.0, configfile: tox.ini, testpaths: testing
plugins: xdist-2.1.0, hypothesis-4.23.8, flaky-3.6.1, forked-1.3.0
collected 161 items

testing/acceptance_test.py ..............s..x.......xx...............F.........x....................................                                                 [ 55%]
testing/test_dsession.py ........x...x                                                                                                                               [ 63%]
testing/test_looponfail.py ...........x.ss                                                                                                                           [ 72%]
testing/test_newhooks.py ..                                                                                                                                          [ 73%]
testing/test_plugin.py ..............                                                                                                                                [ 82%]
testing/test_remote.py x....x.....                                                                                                                                   [ 89%]
testing/test_workermanage.py ........x.......s                                                                                                                       [100%]

================================================================================= FAILURES =================================================================================
________________________________________________________ TestWarnings.test_warning_captured_deprecated_in_pytest_6 _________________________________________________________

self = <acceptance_test.TestWarnings object at 0x7ff94759c4f0>, testdir = <Testdir local('/tmp/pytest-of-tkloczko/pytest-71/test_warning_captured_deprecated_in_pytest_60')>

    def test_warning_captured_deprecated_in_pytest_6(self, testdir):
        """
        Do not trigger the deprecated pytest_warning_captured hook in pytest 6+ (#562)
        """
        import _pytest.hookspec

        if not hasattr(_pytest.hookspec, "pytest_warning_recorded"):
            pytest.skip("test requires pytest 6.0+")

        testdir.makeconftest(
            """
            def pytest_warning_captured():
                assert False, "this hook should not be called in this version"
        """
        )
        testdir.makepyfile(
            """
            import warnings
            def test():
                warnings.warn("custom warning")
        """
        )
        result = testdir.runpytest("-n1")
>       result.stdout.fnmatch_lines(["* 1 passed in *"])
E       Failed: remains unmatched: '* 1 passed in *'

/home/tkloczko/rpmbuild/BUILD/pytest-xdist-2.1.0/testing/acceptance_test.py:787: Failed
--------------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/_pytest/pytester.py", line 1052, in runpytest_inprocess
    reprec = self.inline_run(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/_pytest/pytester.py", line 1019, in inline_run
    ret = pytest.main(list(args), plugins=plugins)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.8/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1280, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1186, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.8/site-packages/_pytest/warnings.py", line 139, in pytest_load_initial_conftests
    yield
  File "/usr/lib64/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/lib/python3.8/site-packages/_pytest/warnings.py", line 64, in catch_warnings_for_item
    ihook.pytest_warning_captured.call_historic(
  File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 308, in call_historic
    res = self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/tmp/pytest-of-tkloczko/pytest-71/test_warning_captured_deprecated_in_pytest_60/conftest.py", line 2, in pytest_warning_captured
    assert False, "this hook should not be called in this version"
AssertionError: this hook should not be called in this version
assert False
========================================================================= short test summary info ==========================================================================
SKIPPED [3] ../../../../../usr/lib/python3.8/site-packages/_pytest/pytester.py:1397: could not import 'pexpect': No module named 'pexpect'
SKIPPED [1] ../../../../../usr/lib/python3.8/site-packages/_pytest/config/__init__.py:1470: no 'gspecs' option found
XFAIL testing/acceptance_test.py::TestDistEach::test_simple_diffoutput
  reason: [NOTRUN] other python versions might not have py.test installed
XFAIL testing/acceptance_test.py::test_terminate_on_hangingnode
XFAIL testing/acceptance_test.py::test_session_hooks
  reason: [NOTRUN] works if run outside test suite
XFAIL testing/acceptance_test.py::TestNodeFailure::test_each_multiple
  #20: xdist race condition on node restart
XFAIL testing/test_dsession.py::TestDistReporter::test_rsync_printing
XFAIL testing/test_dsession.py::test_pytest_issue419
  duplicate test ids not supported yet
XFAIL testing/test_looponfail.py::TestLooponFailing::test_looponfail_removed_test
  broken by pytest 3.1+
XFAIL testing/test_remote.py::test_remoteinitconfig
  #59
XFAIL testing/test_remote.py::TestWorkerInteractor::test_happy_run_events_converted
  reason: implement a simple test for event production
XFAIL testing/test_workermanage.py::TestNodeManager::test_rsync_roots_no_roots
  reason: [NOTRUN]
FAILED testing/acceptance_test.py::TestWarnings::test_warning_captured_deprecated_in_pytest_6 - Failed: remains unmatched: '* 1 passed in *'
===================================================== 1 failed, 146 passed, 4 skipped, 10 xfailed in 109.31s (0:01:49) =====================================================
```

**Comment by bnavigator** [comment] 2020-10-13 12:05
Same for openSUSE since pytest 6.1. (or is the above rpmbuild log from openSUSE?)

- https://build.opensuse.org/package/show/devel:languages:python:pytest/python-pytest-xdist
- [pytest-xdist_stagingH_log.txt](https://github.com/pytest-dev/pytest-xdist/files/5371142/pytest-xdist_stagingH_log.txt)


Should mention that they add a patch to revert d153e0a4c4b764c821da9907ba3d2cac31bc3884, but even without the patch the build fails.

**Comment by kloczek** [comment] 2020-10-13 12:32
> Should mention that they add a patch to revert [d153e0a](https://github.com/pytest-dev/pytest-xdist/commit/d153e0a4c4b764c821da9907ba3d2cac31bc3884), but even without the patch the build fails.

Issue is that I'm using pytest 6.1.1. Theoretically remove compatibility with older pytest should not be kind of problem ..

**Comment by bnavigator** [comment] 2020-10-13 12:38
I know, same for the openSUSE update. But the patch reintroduces the old hooks, so I thought I mention that.

**Comment by nicoddemus** [comment] 2020-10-29 15:57
Some context:

1. `pytest_warning_captured` was introduced in 4.x (don't remember exactly), however in hindsight the hook signature was not fully compatible with pytest-xdist (for reasons not relevant here)

2. `pytest_warning_recorded` was introduced in 5.x, resolving the compatibility issues with pytest xdist. At this time, pytest would trigger both hooks, and pytest-xdist (for backward compatibility) would implement one hook _or_ the other, but not both.

3. In pytest-xdist 2.1.0 we removed support for older pytest, and only implement `pytest_warning_captured`, so it seems that's the reason for the failing test.

From my POV I'm not sure there's any action to be done on pytest-dist side: the project has decided to drop support for older pytest versions for maintainability reasons, so it is expected things will break if the patch that reverts the support ends up breaking some tests.

**Comment by bnavigator** [comment] 2020-10-30 12:14
> 1. `pytest_warning_captured` was introduced in 4.x (don't remember exactly), however in hindsight the hook signature was not fully compatible with pytest-xdist (for reasons not relevant here)
> 2. `pytest_warning_recorded` was introduced in 5.x, resolving the compatibility issues with pytest xdist. At this time, pytest would trigger both hooks, and pytest-xdist (for backward compatibility) would implement one hook _or_ the other, but not both.

The code in d153e0a says it was 3.8 and 6.0.

> 3. In pytest-xdist 2.1.0 we removed support for older pytest, and only implement `pytest_warning_captured`, so it seems that's the reason for the failing test.

> 
> From my POV I'm not sure there's any action to be done on pytest-dist side: the project has decided to drop support for older pytest versions for maintainability reasons, so it is expected things will break if the patch that reverts the support ends up breaking some tests.

That's fine, but as mentioned, the test fails for pytest 6.1 even without the reversion patch. In fact, the patch only has an effect for older pytest versions. That's what the `if ... elif ...` is for.

Apparently since pytest 6.1 the "pytest_warning_captured" hook defined by the test in conftest.py is called in any case. Whether you define the hook for xdist in remote.py or not.

**Comment by tj90241** [comment] 2020-11-07 15:38
So I was interested in this bug, and think I found the crux of the issue.  @nicoddemus -

`pytest_warning_captured` may actually be alive still in `pytest>=6`, as **I was able to get this test to pass** after compiling this call out of `pytest>=6`:
https://github.com/pytest-dev/pytest/blob/master/src/_pytest/warnings.py#L64

Should it not only be triggering one of those warnings?

Same here?
https://github.com/pytest-dev/pytest/blob/master/src/_pytest/config/__init__.py#L1324

**Comment by nicoddemus** [comment] 2020-12-12 15:05
Hi @bnavigator,

Sorry about the long delay here.

You are absolutely correct. I found the cause of the problem and it will be fixed in #609.

Thanks to you both for the report. 👍

**Closed** 2020-12-13 22:58 UTC
Labels: bug, infrastructure

**Comment by sbraz** [comment] 2020-12-13 23:03
Hi @nicoddemus,

Thanks for the fix, do you plan on releasing a new version soon?

**Comment by nicoddemus** [comment] 2020-12-13 23:09
Yes, as soon as https://github.com/pytest-dev/pytest-xdist/pull/608 is merged. 👍

**Comment by kloczek** [comment] 2020-12-14 00:11
Any chance to make new release soon? :P

**Comment by nicoddemus** [comment] 2020-12-14 12:16
`2.2.0` released. 🎉
