### ISSUE TITLE
After running tests terminal left in broken state

### ISSUE THREAD

**Issue by JelleSmet-TomTom** [pytest-dev/pytest-xdist#891] opened 2023-03-23 20:56 UTC
It seems running:
```
pytest -n auto some_tests.py
```
breaks the terminal. 

It seems xdisk outputs control characters messing up the terminal. No text is displayed anymore when typing.
I have to issue the `reset` command in order to have a normally functioning terminal again.

os: linux
terminals used: kitty, konsole, xterm ...
pytest-xdist version used: `3.2.1`

**Comment by RonnyPfannschmidt** [comment] 2023-03-23 21:32
more context needed, xdist itself doesnt do that

**Comment by smetj** [comment] 2023-04-06 10:39
I believe you are right that xdist is not the cause. I have been able to zoom into the cause which is described in this (old) bug report cpything https://github.com/python/cpython/issues/66852.
The tests I run through pytest-xdist make use of `subprocess`.  Somehow my terminal settings are altered after finishing multiple tests (which are then run in parallel by xdist)

My `stty -a` diff output before running the tests and after:

```
$ diff before after
9c9
< isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
---
> isig -icanon iexten -echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
``` 

The shell command I execute inside my tests is for example `nmap -oG - -sP smetj.net` ...
Inspecting the output of that command I cannot see any control characters being emitted (checked with `less --raw-control-chars`)

Running xdist surfaces the problem but its not a `xdist` issue as I believe the issue is underneath ...

Feel free to close bug report as you seem fit. Tnx for the feedback!

**Comment by RonnyPfannschmidt** [comment] 2023-04-06 10:47
Closing au other Software being responsible

**Closed** 2023-04-06 11:00 UTC
Labels: needs information
