### ISSUE TITLE
`pytest-xdist` breaks asyncio-based code expecting to be run in the main thread

### ISSUE THREAD

**Issue by webknjaz** [pytest-dev/pytest-xdist#620] opened 2021-01-25 00:10 UTC
When `asyncio`-based software needs to register [`signal`](https://docs.python.org/3/library/signal.html) handlers, calling `add_signal_handler()` only works when the current thread is main and raises a `RuntimeError` otherwise.

When I first tried integrating `pytest-xdist` into `aiohttp`'s test suite a few years ago, we've faced a problem that about 15% of pytest invocations would hit this and had to disable the plugin:
* https://github.com/aio-libs/aiohttp/pull/3419
* https://github.com/aio-libs/aiohttp/issues/3450

The reproducer is to clone aio-libs/aiohttp, add `-n auto` to `addopts` somewhere in `setup.cfg`, and re-run `make test` until you see the traceback. On aiohttp side, it's coming from the [`watcher.attach_loop()` call](https://github.com/aio-libs/aiohttp/blob/742a8b6/aiohttp/test_utils.py#L510) invoked from the pytest plugin @ https://github.com/aio-libs/aiohttp/blob/742a8b6/aiohttp/pytest_plugin.py#L161.

Now that I've had some time to try to debug what's happening, I've stuck a debugger right before the [line that raises `RuntimeError`](https://github.com/python/cpython/blob/8dfe156/Lib/asyncio/unix_events.py#L107) and confirmed that the thread wasn't main:
```python
>>> import threading
>>> threading.enumerate()
[<_MainThread(MainThread, started 140666216200000)>, <_DummyThread(Dummy-1, started daemon 140666196751936)>]
>>> threading.current_thread()
<_DummyThread(Dummy-1, started daemon                 
140666196751936)>
```

@asvetlov It should be possible to fix this on the `asyncio` side with [`ThreadedChildWatcher`](https://docs.python.org/3/library/asyncio-policy.html#asyncio.ThreadedChildWatcher) (https://bugs.python.org/issue35621 / https://github.com/python/cpython/pull/14344) but it only appeared in the stdlib since Python 3.8: https://stackoverflow.com/a/58614689/595220.

It's hard to pinpoint where that thread is coming from but it appears to be `execnet`'s fault: https://github.com/pytest-dev/pytest-xdist/blob/c5fadcd734b008251fbaa438e0806235d9bd081b/src/xdist/workermanage.py#L41 + https://github.com/pytest-dev/execnet/blob/116637ab183bc078647f281b52e662650e8178e7/execnet/multi.py#L27.

@nicoddemus do you have any insight into this? I'm rather lost at this point. Is there any way to avoid this race condition?

**Comment by RonnyPfannschmidt** [comment] 2021-01-25 05:21
This is a issue that was Int to execnet with the addition of thread models for gevent /eventlet. 

A workaround is to downgrade execnet.

Execnet currently is unmaintained.

**Comment by webknjaz** [comment] 2021-01-25 09:50
I tried looking into it and thought that maybe using `hasprimary=True` would help (https://github.com/pytest-dev/execnet/blob/116637a/execnet/gateway_base.py#L165) but it just gets stuck on worker allocation...

@RonnyPfannschmidt is there a known `execnet` version I need to downgrade to?

**Comment by webknjaz** [comment] 2021-01-25 10:02
Tried `execnet<1.2` but that's too old for modern Python and it explodes trying to call deprecated `isAlive()`.

Sounds like we'll need a backport of `ThreadedChildWatcher` after all.

@RonnyPfannschmidt do you think there's any reasonable way to have a fixture forcing xdist to bypass scheduling a specific test in workers and just execute it in the main process?

**Comment by RonnyPfannschmidt** [comment] 2021-01-25 10:58
When using xdist, no test run in the main process

**Comment by graingert** [comment] 2021-01-25 11:01
arn't tests in xdist workers also run in only the main thread?

**Comment by RonnyPfannschmidt** [comment] 2021-01-25 11:03
So there is no reasonable way

**Comment by graingert** [comment] 2021-01-25 11:06
>  I've stuck a debugger right before the line that raises RuntimeError and confirmed that the thread wasn't main:

@webknjaz which process was running the breakpoint()? the xdist leader or an xdist worker?

you should be able to track the stack of what created the  <_DummyThread(Dummy-1, started daemon 140666196751936)> with tracemalloc

**Comment by RonnyPfannschmidt** [comment] 2021-01-25 11:07
@graingert an addition to execnet broke that assumption

**Comment by graingert** [comment] 2021-01-25 11:08
@RonnyPfannschmidt do you have a link to the commit that introduced it?

**Comment by RonnyPfannschmidt** [comment] 2021-01-25 11:10
Not right now, I'm on mobile atm, and no longer a maintainer for execnet

**Comment by webknjaz** [comment] 2021-01-25 11:12
@graingert can't do that right now but I think the thread is spawned by this call https://github.com/pytest-dev/execnet/blob/116637ab183bc078647f281b52e662650e8178e7/execnet/gateway_base.py#L315

**Comment by graingert** [comment] 2021-01-25 11:49
so it looks like pytest-xdist will run tests on the main thread *almost* all the time, it's only if there are concurrent remote_exec calls that execnet will actually spawn a thread, eg we always want to hit: https://github.com/pytest-dev/execnet/blob/116637ab183bc078647f281b52e662650e8178e7/execnet/gateway_base.py#L299-L302

so I had a look around for places that remote_exec is called without an associated wait_close, and only found:

```python
diff --git a/execnet/gateway.py b/execnet/gateway.py
index 8e2c1de..8a0da92 100644
--- a/execnet/gateway.py
+++ b/execnet/gateway.py
@@ -75,7 +75,10 @@ class Gateway(gateway_base.BaseGateway):
         """ return some sys/env information from remote. """
         if update or not hasattr(self, "_cache_rinfo"):
             ch = self.remote_exec(rinfo_source)
-            self._cache_rinfo = RInfo(ch.receive())
+            try:
+                self._cache_rinfo = RInfo(ch.receive())
+            finally:
+                ch.wait_close()
         return self._cache_rinfo
 
     def hasreceiver(self):
-- 
2.30.0
```

**Comment by webknjaz** [comment] 2021-01-25 11:50
Maybe, to verify that we'd have to run a lot of parallel pytest invocations with the "is main thread" check. I'll try to do this when I have a minute.

**Comment by graingert** [comment] 2021-01-25 11:52
it looks like fixing this test will fix the problem properly: https://github.com/pytest-dev/execnet/blob/116637ab183bc078647f281b52e662650e8178e7/testing/test_threadpool.py#L77-L103

**Comment by webknjaz** [comment] 2021-01-26 10:32
> maybe this patch will help?

@graingert
This patch breaks everything:
> INTERNALERROR> AttributeError: 'Channel' object has no attribute 'wait_close'

**Comment by graingert** [comment] 2021-01-26 11:31
@webknjaz sorry that's a typo it's `waitclose()`

```python
diff --git a/execnet/gateway.py b/execnet/gateway.py
index 8e2c1de..8a0da92 100644
--- a/execnet/gateway.py
+++ b/execnet/gateway.py
@@ -75,7 +75,10 @@ class Gateway(gateway_base.BaseGateway):
         """ return some sys/env information from remote. """
         if update or not hasattr(self, "_cache_rinfo"):
             ch = self.remote_exec(rinfo_source)
-            self._cache_rinfo = RInfo(ch.receive())
+            try:
+                self._cache_rinfo = RInfo(ch.receive())
+            finally:
+                ch.waitclose()
         return self._cache_rinfo
 
     def hasreceiver(self):
-- 
2.30.0
```

maybe this patch will help?

**Comment by webknjaz** [comment] 2021-01-26 14:41
@graingert that last patch seems to fix this.

**Comment by graingert** [comment] 2021-01-26 14:46
@webknjaz I don't think it's quite right, because there's a very small window between when the channel is closed and the primary_thread_task_ready semaphore is set

but it should improve things a lot

**Comment by graingert** [comment] 2021-01-26 16:56
Related to https://github.com/pytest-dev/execnet/issues/96

**Comment by mattgodbolt** [comment] 2021-03-25 17:37
Hey folks. Apologies, this is a cross-post from the execnet issue, but here for visibility:

 wondered if this issue might explain a super-intermittant issue we see.

We're using xdist 1.32, and execnet 1.7.1.

In async tests super rarely we get errors saying RuntimeError: There is no current event loop in thread 'Dummy-1' - which I've traced back to the tests not running on the main thread (and thus not having a default event loop). It seems like this is the same issue - a rare case where tests get run on the "wrong" thread.

Would you concur, and do you have any advice for how to work around it? Thanks in advance.

**Comment by graingert** [comment] 2021-03-25 17:40
@mattgodbolt try execnet 1.8.0?

**Comment by mattgodbolt** [comment] 2021-03-25 18:01
Thanks @graingert I can try. It's so rare, I was reluctant to "just" try it as I'll never know if it really fixed it. But if you think it'll help, and my description doesn't seem far off; I'll give it a go: thanks!

**Comment by RonnyPfannschmidt** [comment] 2021-03-25 18:02
at some execnet version the threadmodel concept got added, since then this stuff is broken

execnet currently is unmaintained, an older version might work

**Comment by mattgodbolt** [comment] 2021-03-25 18:02
Thanks @RonnyPfannschmidt .
>  an older version might work
It's been asked above, how old is old?

**Comment by webknjaz** [comment] 2021-03-25 18:03
I think when I last tried it, the new version made this exception rarer but didn't eliminate it completely AFAIR

**Comment by mattgodbolt** [comment] 2021-03-25 18:03
Thanks for the info @webknjaz

**Comment by RonnyPfannschmidt** [comment] 2021-03-25 18:07
https://github.com/pytest-dev/execnet/blob/master/CHANGELOG.rst#12

 1.2 added it

seems like this will be a major pain

**Comment by nicoddemus** [comment] 2021-03-26 11:48
Has this been fixed by `execnet-1.8.0`? Did anybody else encountered this problem again after updating?

**Comment by nicoddemus** [comment] 2021-03-26 12:25
I just confirmed: before `execnet-1.8.0`, we would get this an error related to dummy threads a few times per week. Since updating to `1.8.0` in late January, we never got the error again.

Closing this as solved now then. All credits go to @graingert for finding the problem and providing a PR. 👍

**Comment by mattgodbolt** [comment] 2021-03-26 13:03
Fantastic: thanks all. We upgraded to 1.8.0 and I'm now very hopeful it's fixed.

**Comment by mattgodbolt** [comment] 2021-03-26 19:22
Sorry to be the bearer of bad news, but we just had a failure of the type I described above (an asynio test failing with `RuntimeError: There is no current event loop in thread 'Dummy-1'`), with `pytest-xdist 1.33.0` and `execnet 1.8.0` from conda.

**Comment by webknjaz** [comment] 2021-03-29 22:04
@nicoddemus could you reopen this? Here's an example failure with `execnet==1.8.0` from today: https://github.com/sanitizers/octomachinery/runs/2222647186#step:7:400.

**Comment by nicoddemus** [comment] 2021-03-31 18:53
Ahh that's a bummer.

In my case we are not really using `asyncio`, but were experiencing the problem of spawning code not in the main thread.

Thanks folks for the feedback.

**Comment by altendky** [comment] 2022-09-04 14:34
So we reopened this but without reopening the linked upstream issue https://github.com/pytest-dev/execnet/issues/96 nor referencing another.  Does something need to be bumped in execnet to work on this?  I've hit it at work and just got a report at https://github.com/pytest-dev/pytest-twisted/issues/153.

**Comment by RonnyPfannschmidt** [comment] 2022-09-04 14:49
Needs a breaking release of execnet, i intend to eventually do that, but it's a not soon item

**Comment by zmedico** [comment] 2024-02-16 06:57
I have a proposed solution for this issue in https://github.com/pytest-dev/execnet/pull/243 and I'm getting positive results when I [patch pytest-xdist to use it](https://github.com/zmedico/pytest-xdist/pull/1).

**Comment by nicoddemus** [comment] 2024-04-19 11:04
This will be available in the next release. 👍

**Closed** 2024-04-19 11:03 UTC

**Comment by webknjaz** [comment] 2024-04-19 21:28
FTR the new release of pytest-xdist 3.6.0 explodes in a project that does not use async: https://github.com/pytest-dev/pytest-xdist/pull/1070#issuecomment-2067290245. It seems like it brings some compatibility issues with pytest itself or pytest-cov (which I also see being mentioned in the traceback)...

**Comment by zmedico** [comment] 2024-04-19 22:00
> FTR the new release of pytest-xdist 3.6.0 explodes in a project that does not use async: [#1070 (comment)](https://github.com/pytest-dev/pytest-xdist/pull/1070#issuecomment-2067290245). It seems like it brings some compatibility issues with pytest itself or pytest-cov (which I also see being mentioned in the traceback)...

This looks like a pretty small issue. In pytest-cov it calls `node.gateway._rinfo()` and this method triggers a deadlock error for the main_thread_only execmodel when the gateway is already busy with another remote_exec call, since _rinfo calls remote_exec here:

https://github.com/pytest-dev/execnet/blob/v2.1.1/src/execnet/gateway.py#L85
