### ISSUE TITLE
Sporadic crashes on PyPy since upgrade to 3.2.0

### ISSUE THREAD

**Issue by jab** [pytest-dev/pytest-xdist#882] opened 2023-02-26 16:04 UTC
5 days ago I [upgraded from 3.1.0 to 3.2.0](https://github.com/jab/bidict/commit/d1b8c871ec046d668cf523ba14be6c55423ce116#diff-e88c8a995e11decbe943d0046c316f2cc891916620433ce5088da4623039d262R173).

Since then I've continued to run a nightly CI job, and [three](https://github.com/jab/bidict/actions/runs/4270832569/jobs/7434886888#step:8:380) of the [runs](https://github.com/jab/bidict/actions/runs/4234711135/jobs/7364288283#step:8:368) against [PyPy](https://github.com/jab/bidict/actions/runs/4234711135/jobs/7364288283#step:8:357) crashed with "node down: Not properly terminated" right as they were finishing up an otherwise successful run. For each of those three times, the same job eventually succeeded after retrying.

I never saw this before upgrading, so I wonder if this was introduced in 3.2.0? Please let me know if there is any other info I can provide, and hope this bug report helps. In the meantime, I will try pinning to 3.1.0 and update this issue if I still see this occurring.

**Comment by amezin** [comment] 2023-02-27 12:07
The complete error message was

```
Fatal Python error: Aborted

Stack (most recent call first, approximate line numbers):
  File "/home/runner/work/bidict/bidict/.tox/py/lib/pypy3.9/site-packages/hypothesis/vendor/pretty.py", line 636 in _repr_pprint
tests/property_tests/test_properties.py::test_views 
[gw0] node down: Not properly terminated
[gw0] [100%] FAILED tests/property_tests/test_properties.py::test_views
```

in all cases.

Worker number and pypy version were different sometimes, but it's always "Fatal Python error: Aborted", with `_repr_pprint` from hypothesis in the stack trace and `tests/property_tests/test_properties.py::test_views`.

From the other side: there weren't many changes in 3.2.0. The only ones that may affect test runs without any configuration changes seem to be:

- https://github.com/pytest-dev/pytest-xdist/commit/9b0b5b1495b024940e3f5c71583711be46df255b
- https://github.com/pytest-dev/pytest-xdist/pull/862/commits/b6d6c4d44b52f30cf2db74af844cb33066b4fde0

**Comment by amezin** [comment] 2023-02-28 18:56
@jab Looks like you have the same crash with 3.1.0 too https://github.com/jab/bidict/actions/runs/4295104017/jobs/7485050518

**Comment by jab** [comment] 2023-03-01 02:48
Indeed! Undid the rollback to 3.1.0.

Worth mentioning that I updated to pytest-xdist 3.2.0 at the same time that I updated other dependencies, e.g. to pytest 7.2.1 from 7.2.0 and to hypothesis 6.68.2 from 6.61.0. I could try undoing all those updates, and then the could be applied one at a time to try to pinpoint this, but that might take a while, especially since this doesn't reproduce reliably.

Please let me know if you have any better ideas here. Does the combination of the "node down: Not properly terminated" error and "only occurs on PyPy" provoke any intuitions?

**Comment by amezin** [comment] 2023-03-01 19:47
> Please let me know if you have any better ideas here. Does the combination of the "node down: Not properly terminated" error and "only occurs on PyPy" provoke any intuitions?

`node down: Not properly terminated` means the worker process disconnected without proper shutdown. `Fatal Python error: Aborted` makes it more specific - Python interpreter crashed while executing the test. Usually, you have to use ctypes/cffi/C extension to cause that.

At least, it's definitely not a bug in pytest-xdist, so I'm closing the issue.

**Closed by amezin** 2023-03-01 19:47 UTC

**Comment by jab** [comment] 2023-03-13 23:35
Thanks @amezin. Since bidict (and the test exercising it when the crashes occur) are implemented in pure Python, I've reported this to PyPy in https://foss.heptapod.net/pypy/pypy/-/issues/3904.
