### ISSUE TITLE
pytest-bdd unable to recognize -n argument

### ISSUE THREAD

**Issue by Enigmaderockz** [pytest-dev/pytest-xdist#845] opened 2022-11-19 20:30 UTC
I am using below command to run pytest-bdd tests 

``
pytest-bdd -sv test_test1.py
``
but when i use -n argument to run pytest-bdd tests in parallel, pytest-bdd is not recognizing -n argument

``
pytest-bdd -sv -n 3 test_test1.py
``

**Comment by RonnyPfannschmidt** [comment] 2022-11-19 21:01
It's not clear what you are asking for, this plugin is for pytest, not for pytest-bdd

**Comment by RonnyPfannschmidt** [comment] 2022-11-19 21:04
As far as I can tell the docs for pytest-bdd also recommend running pytest, please elaborate what you actually do

**Comment by Enigmaderockz** [comment] 2022-11-21 19:16
okay. If you know how can I integrate pytest-bdd with pytest-xdist then it would be very helpful. As far as I know, I can see only pytest usage with this xdist package.

it would be great if we can use pytest-xdist with pytest-bdd framework.

**Comment by nicoddemus** [comment] 2022-11-22 11:00
Closing as duplicate of https://github.com/pytest-dev/pytest-bdd/issues/584, moving the discussion over there.

**Closed by nicoddemus** 2022-11-22 11:00 UTC
Labels: question, needs information
